### PR TITLE
Switch to minima 3.0 theme

### PR DESCRIPTION
**Pull request by djhoese**
This is major rewrite of the website in its structure, but overall it is for the better in my opinion. I'll try to layout what I did in some kind of organized description below.

## Purpose

This PR switches from the jekyll-theme-midnight to the jekyll default theme "minima". This theme provides a lot more functionality than the old one including a navigation bar and easier customization.

## Theme

I switched this to "minima" originally which uses the latest stable release of the theme and is the same as what github pages uses. However, this is version 2.5.1 which doesn't provide a lot of functionality that the current in-progress minima 3.0 theme does. So I found a github issue that pointed out that you could use a remote theme on github pages and just point it to the github repository for the minima 3.0 theme.

In addition to just changing the theme, I configure the theme to use the "dark" skin which makes the result very very close to the old site but with the same minima features.

## Navigation Bar

I had to think about what should be included in the navigation bar or else we'd just have a ton of pages there. I decided on:

* Pytroll (the home page)
* Software (new page, see below)
* Community (new page, see below)
* Gallery
* Code of Conduct

The Software and Community pages are new and right now are just a bulleted list of links to various things including other pages on the site. These essentially replace the "Links" that were on the bottom of the home page in the current version of the site. These could be improved, but since the previous "Links" section was just a list of links I'd say this is only adding organization to them.

## Posts/Announcements/Blog

One thing we can do now with the minima theme is easily create individual dated "blog posts" in a `_posts` directory that will be listed and optionally paginated on the home page. We could use these for things like announcements (PCWs, new package versions, new big features in packages, etc). Basically for pages that are more blog-like and temporary and not "about us"-type pages.

## Code of Conduct

The CoC section in the current home page is long and a little too business-y for the home page. I've moved it to a "coc_info.md" page that then links to the actual Code of Conduct document.

### Home Page

image

### Footer

image

### Software Page

image

### Community Page

image

### CODE REVIEW

**Comment by djhoese** [comment]
One thing I still haven't done and probably won't do in this PR is get anchors added to each section. Turns out this is pretty hard to do in jekyll cleanly (requires javascript or awkward template changes).

**Comment by mraspaud** [comment]
Looks good! Should use the opportunity to put a satellite image on the front page?
Also is the slack subscription button still clearly visible on the front page?

**Comment by adybbroe** [comment]
Looks really good @djhoese A clear improvement I would say. Thanks a lot for doing this!
From a quick consideration I agree with your choice of navigation bar content. I echo @mraspaud 's too comments/questions. A "join us on Slack" button should be easily found.

**Comment by gerritholl** [comment]
Looks good.  What do you plan under „gallery“?

**Comment by sfinkens** [comment]
Awesome, thanks a lot! Good idea to put a satellite image on the front page. Or should that go to the gallery?

**Comment by sjoro** [comment]
looks good to me dave! thanks for the update. i kind of have the same comment about having a satellite image in the front page. something hi-res and colourful (pretty picture! ;)), with coastlines and maybe pytroll logo in the image would be my suggestion.

**Comment by djhoese** [comment]
@gerritholl the gallery is already on the current website and points to some examples in pytroll-examples. Problem is since the images went away on that repository there are a ton of missed images here. Now that I think about it, maybe it is better to not have a gallery here.

As for the satellite image, someone give me one or a couple to use and I'll put it on there. We could even do a carousel of images if you really wanted to.

**Review by adybbroe — APPROVED** [review]
As already said, looks very good. Go ahead and consider the few comments and suggested.

**Comment by mraspaud** [comment]
How about this one, taken from PR #1674 ? https://user-images.githubusercontent.com/57386258/120970755-2f32e180-c7af-11eb-96ef-e634ad86b676.png

**Comment by djhoese** [comment]
Regarding the slack icon:

image

**Comment by djhoese** [comment]
@mraspaud I could try making one too. Where/how should it be placed? Right under the pytroll logo? Should it be relatively small or should it be pretty large? Centered on the page I assume.

**Comment by djhoese** [comment]
With this last set of commits the section headers now have little links on the left so you can easily get access to the direct link to that section:

image

**Comment by djhoese** [comment]
@mraspaud Thoughts:

image

**Comment by djhoese** [comment]
Here is a live version of the site that you can explore https://www.ssec.wisc.edu/~davidh/tmp/pytroll_site/

Note I have to manually update this and had to add special parameters to the build to make it link correctly. I think it is working, but there may be some hiccups.

**Comment by djhoese** [comment]
Based on the comments here which I've addressed and the comments on slack, I'm going to merge this and we'll see what breaks on github pages.

**Pull request merged**
