### PR TITLE
Fix image for seviri gallery example

### PR DESCRIPTION
**Pull request by mraspaud**
This PR links to kaggle image and notebook for the seviri quickstart

### CODE REVIEW

**Comment by djhoese** [comment]
Is it possible (if not done already) to point kaggle to the notebook in pytroll-examples so there is only one copy of this notebook?

**Comment by mraspaud** [comment]
@djhoese I looked this morning, and couldn't find a way to do it. I did import the existing notebook into kaggle originally, but yeah, it's not solving that problem. One solution would be to remove the corresponding pytroll example notebook, or replace it with an empty one pointing to kaggle.

**Comment by djhoese** [comment]
Yeah a quick googling makes it seem not possible. This is too bad.

What data did you use for the examples? Is it accessible from EWC? Could we run the notebooks as a test and host the images from there?

**Comment by mraspaud** [comment]
The data is hosted on kaggle, and we can use the kaggle CLI if we want to download the data on EWC. So yeah, we should be able to use the notebook as a test

**Comment by djhoese** [comment]
Ah ok. I see. I was thinking again of having EUMETSAT mount some storage to access SEVIRI data directly. I'm ok with this being merged, but I'm still hoping for us to come up with something better in the near future.

**Pull request merged**
